server:
    port: 9050

naver:
  client:
    id: LDKImDi4wi3RBeQEUDOD
    secret: Rk4o4SkAu6
  url:
    search:
      image: https://openapi.naver.com/v1/search/image
      local: https://openapi.naver.com/v1/search/local.json


spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/seeder
    username: root
    password: 1234
